### ISSUE TITLE
Add mock modules

### ISSUE THREAD

**Issue by gneeser** [puhep/pudb2#13]
Much like the #10 issue, we should add mock modules (called silicon in the google doc if I recall correctly). They should be displayed and added in much the same way as the thermal sensors are added. To this end, I can either add mock modules to the sensor table and update my nomenclature or add new tables in the mysql. Which is best will depend on some input from others on various criteria, which can be discussed at the weekly meeting.

**Comment by NickHinton** [comment]
- Geometry (2x2, 1x2, 1x1)

- Si thickness

- Adhesive

- Notes

- Layout of objects

**Comment by gneeser** [comment]
What units do we want on the silicon thickness?

**Comment by NickHinton** [comment]
Microns.
