### ISSUE TITLE
Error Page When Clicking on Uploaded Pictures

### ISSUE THREAD

**Issue by NickHinton** [puhep/pudb2#14]
Looking at this page: 
http://inky.physics.purdue.edu/cmsfpix//phase_2/sheet.php?id=4 

I tried to click on one of the pictures for a larger view. Doing so redirected me to this error:

http://inky.physics.purdue.edu/cmsfpix//phase_2/pics/sheet/4/8

Maybe a URL issue?

**Comment by gneeser** [comment]
Looks like it doesn't like urls with spaces. It should be a pretty simple fix (I recall the exact function).

**Comment by gneeser** [comment]
Got it. Let me know if there's any more trouble with it.
