### ISSUE TITLE
thickness plot vs time

### ISSUE THREAD

**Issue by ajung42** [puhep/pudb2#18]
great to see the thickness plot versus time - do we also have that for the 8-plies ?
If not can we implement that one....

thanks
andy

**Comment by ChaseNelson** [comment]
thickness plot for 8-plies is up

**Comment by ajung42** [comment]
From where in the data base would I find the thickness vs time plot ? I would have thought there is a link from each individual ply or at least from the Part List "Sheet" table ?!
