### ISSUE TITLE
Thermal Sensor page

### ISSUE THREAD

**Issue by gneeser** [puhep/pudb2#2]
Each thermal sensor should have its own page with its information, including:

- [x] Sensor type (e.g. thermistor, old RTD, new RTD)
- [x] What channel it is connected to (what is the naming scheme like? From the logbook, it seems we'll have three-digit integers. Should I have a list to select from?)

- [x] Calibration Data (what form would this take? is it a single parameter, a string, or a whole array/file?)

- [x] The support structure it is currently on (if that's a thing either, just spitballing here)

I encourage others who know more to comment here with requests.

**Comment by AndySpring** [comment]
Hey Greg
I tried to edit the channel of the thermistors from the parts page but there is no option or means to do so. Not sure if thats something youre still trying to complete. here is the page i see when i try to give it a channel

![databasesensorchannelerror](https://cloud.githubusercontent.com/assets/26171360/23564619/9b9dd1b2-0018-11e7-8c84-b28eec20333e.PNG)

Thanks again

**Comment by gneeser** [comment]
Yeah, that's something that's still in the works. As of now, the channel is only on a per-test basis.

**Comment by gneeser** [comment]
You can now view and edit the current channel on each sensor's page. Next up is automatically populating the current channel when submitting a new test.

**Comment by gneeser** [comment]
Check out the test editing page: 
http://inky.physics.purdue.edu/cmsfpix//phase_2_t/test_edit.php?id=16

Right now, if you have a sensor on this page whose channel is unset (for this test), the current channel of the sensor will display like "101 (Default)." The "Default" is to set it apart from a sensor whose channel has been set using the interface. 

At the moment, if you want to associate the default, current channel of the sensor with the test, you still have to manually fill in the data and submit it. Otherwise, we would overwrite old test data with the current values. 

This flow is a little confusing, so if you need clarification let me know. I'll also ponder a better way to implement it, and if you have any thoughts just let me know.
