### ISSUE TITLE
JavaScript Functions

### ISSUE THREAD

**Issue by ChaseNelson** [puhep/pudb2#21]
Find a way to use javascript to call queries to the mySQL database.

**Comment by gneeser** [comment]
Hey Chase,
Javascript itself can't do this as it is purely client side. You could still do this a couple of different ways though. 

- You could run SQL queries in the php at the top of the page, then access them later by putting some php inside javascript. Take a look at the test_edit page for an example of this. It's not super clean, but there it is.

- You could use AJAX, which is probably the recommended method, though I do not have any experience with this myself. 

This is why we initially only used php and html, though more modern methods are of course preferable.

**Comment by ChaseNelson** [comment]
This is how I'm calling the php functions to query the database.
```javascript
$(function() {
    $.ajax({
        url: 'react-data.php?id=' + 3,
        success: function(data) {
            ....
            console.log('It worked');
            ...
        }
    });
};
```
It worked in testing and I will be adding it soon.
