### ISSUE TITLE
Back to thickness vs. time, curing scheme vs. time, new entry for sheet DB

### ISSUE THREAD

**Issue by ajung42** [puhep/pudb2#22]
From where in the data base would I find the thickness vs time plot ? I would have thought there is a link from each individual ply or at least from the Part List "Sheet" table view of all of the sheets we made so far ?!

Related: Can we have an overlay plot for 3-ply and 8-ply that compares the curing times, ramp times on the same plot ? that will allow to track down issues in the sheets when it comes to different thickness.

Also can you add one more field "Vaccum bag checked for leaks" or similar with entries being yes/no. From now on I want us to use a leak sniffer for every bag we close and use.

thanks
andy

**Comment by ChaseNelson** [comment]
If you go to the parts list page and click on 'Sheets'

**Comment by ChaseNelson** [comment]
Bag checked for leaks field is up

**Comment by ChaseNelson** [comment]
What do you want on the new plot?

**Comment by ajung42** [comment]
forgot to sent earlier but yesterday I made a new request with the plots and content I had in mind...hope it is reasonably clear what I want on that plot.

I attach example plots from a past analysis I did 2 years ago with a C macro.

<img width="663" alt="screen shot 2017-06-11 at 9 43 22 am" src="https://user-images.githubusercontent.com/12069217/27011482-801b7a96-4e8a-11e7-86d3-45d45b619f74.png">
<img width="670" alt="screen shot 2017-06-11 at 9 43 08 am" src="https://user-images.githubusercontent.com/12069217/27011484-8344ea2c-4e8a-11e7-8fd7-6d14445fec33.png">
