### ISSUE TITLE
"data analysis" new plots

### ISSUE THREAD

**Issue by ajung42** [puhep/pudb2#23]
Hi Chase

here is what kind of analysis we could use...one difficulty is that we would only need that for data taken with the support structures and silicon mock-up sensors. Maybe a solution could be do provide a box/field one can tick, e.g. "Run analysis" or so.

The following is the kind of analysis needed:
- determine stable/flat regions by having a gradient < 0.5 degree per 100 time steps...this requires some tuning. Indicate those regions on the summary plot you have already made, e.g. red vertical lines or so.
- once those flat, small gradient regions are identified, average all timestamps in that area meaning 100, 500 or X timestamps, depending how long the flat regions is. this gives you one new data point
per sensor and "flat/stable" regions.
- create a plot of these individual data points (of course these are averaged Temps) and plot them against the sensor ID or location if we have that info available in the raw data.
- next step, and so far we do not have that kind of setup/result, you would subtract the "inlet Co2 compressor" temperature which would just be one column in the spreadsheet from all of the averaged temps per stable/flat region. That way you get DeltaTs, hope that makes sense so far.
- plot all of those DeltaTs again as function of sensor ID or location if available.

cosmetic and other fine tunings:
- axis labels need to be larger, have an all white bg but some kind of grid lines in x and y
- can assign a statistical uncertainty based on the number of time stamps you average. Meaning if you have averaged 100 time stamps assign sqrt(100)=10, yields a relative uncertainty of 10% so if your average Temp for that point is 15 degree the point has an error of 1.5 degree. Hope that makes sense.

**Comment by ChaseNelson** [comment]
I made the graph of the average of the 'flat' regions. http://inky.physics.purdue.edu/cmsfpix////phase_2_t/php/dataAnalysis.php?id=33
Let me know what you think.

**Comment by ChaseNelson** [comment]
I redid the average temperature plots. The now includes the statistics to show the potential change in temperatures. Jesse uploaded some plots so you can see what some new data looks like too.
