### ISSUE TITLE
Thickness data

### ISSUE THREAD

**Issue by wade31** [puhep/pudb2#26]
Hey @ChaseNelson

So we have a series of data point for a sheet thickness measurement. Each point has an xyz value with the z being the thickness. If I upload an excel file with these values is there a way the databse could turn that into a contour map of the sheet? Also could you take the z values and create field for the average thickness as well as the max and min?

**Comment by ChaseNelson** [comment]
I'm pretty sure I can do all of that, just let me know where the file is and what its name is.

**Comment by wade31** [comment]
8ply 3 should have a file named PSDL 8 ply 3 thickness.

________________________________

**Comment by ChaseNelson** [comment]
Hey @wade31,

I tried to make a [contour map](http://www.physics.purdue.edu/cmsfpix////phase_2/php/sheetContour.php?id=16) with the file. The map is also viewable from [the sheet page](http://www.physics.purdue.edu/cmsfpix////phase_2/php/sheetContour.php?id=16) and if you click the title above the graph (Sheet Thickness Contour) it will take you to just the graph.

Let me know what you think and what changes should be made.

**Comment by ChaseNelson** [comment]
Hey @ajung42

I removed the edge from the plots and automatically adjusted the average, min, and max thickness.

**Comment by ajung42** [comment]
great! works well, the new 8 ply is now 640micron which I feel is realistic. thanks.

cheers
andy


-------------------------------------------------------------------
Andreas Jung - Purdue University
525 Northwestern Ave, West Lafayette, IN, 47907, USA
Office: +1 765 494 5399<https://exchange.purdue.edu/owa/redir.aspx?SURL=B6NDM6dGBbzM7vE2Kt0soUSUCFE8PqgnzVduRgBgXHQYuPtvrazSCG0AYQBpAGwAdABvADoAYQBuAGoAdQBuAGcAQABwAHUAcgBkAHUAZQAuAGUAZAB1AA..&URL=mailto%3aanjung%40purdue.edu>
-------------------------------------------------------------------
________________________________
