### ISSUE TITLE
Averaged Temperatures and graph pictures???

### ISSUE THREAD

**Issue by JesseMcDon** [puhep/pudb2#27]
So, the graph finally uploaded but the graph plot runs out of bounds of the view section. You can see in multiple tests that this occurs. Also, the averaged temperatures are not displayed and this is strange because i do not know why. i edited in the thermal sensors in hopes that it would identify them but it didn't work.

**Comment by ChaseNelson** [comment]
The average temperature graph should not be displayed because it did not detect regions that were flat enough. I fixed this by not showing the graph unless there are flat regions.

**Comment by ChaseNelson** [comment]
The plot models are showing all the sensors it just that you have sensors and heaters at the same location so it draws a sensor then draws a heater on top of it, so you can only see the heater.

**Comment by JesseMcDon** [comment]
Well, what do i do to fix it? what defines a "flat" region? not flat enough!?!?!??!?! Also, yeah, one of the sensors is right on top of the heater. it was an interesting design this time around

**Comment by ChaseNelson** [comment]
I'm trying to find out what's up with the 'flat' regions.

**Comment by ChaseNelson** [comment]
I updated the requirements to be 'flat' and now you have 'flat' regions and the average temp plots
