### ISSUE TITLE
plies vs time

### ISSUE THREAD

**Issue by ajung42** [puhep/pudb2#28]
few questions/comments:
- why is the thickness for the latest plies 0, e.g. for the 3 plies ?
- can we actually extract the average thickness from the contour plot by averaging automatically available data ? potentially need to suppress the outermost "line" of thickness measurements.

**Comment by ChaseNelson** [comment]
They show at 0 because the thickness has not been entered for the sheets.

**Comment by ChaseNelson** [comment]
I can average the thickness automatically from the thickness contour file.

**Comment by ajung42** [comment]
ok, great - is it possible to ignore all measurements between the edges and edges-1.5cm ?

guess, you have not done the automatic tool yet since I do not see the updated thickness plots in the summary vs. time. and also for this plot a bit larger fonts would be nice

**Comment by ChaseNelson** [comment]
I just added the automatic update of sheet thickness.

**Comment by ChaseNelson** [comment]
The plies vs time graphs should be good for now. I'll get work on making them look better.

**Comment by ajung42** [comment]
thanks - just looked at the thickness vs time plot and the latest 8-ply average of 570 micron made me somewhat concerned on how the average is calculated...looking at the contour of that 8-ply itself it seemed all around 630 micron, see http://www.physics.purdue.edu/cmsfpix///phase_2/sheet.php?id=20

maybe my mistake with the comment on ignoring the outer edge area...did you ignore the inner part and only average the outer edge ? anyways just reduce the area by 1.5cm inwards from the edge and average all based on that.

**Comment by ChaseNelson** [comment]
@ajung42 
I just redid temp vs time graphs. Let me know what you think of them.

**Comment by ajung42** [comment]
the averages look nicely plotted...what is the difference between what looks like smaller error data point and on top of it drawn another one with different uncertainties.

also in the more simple plot of the raw data I can not see the ranges anymore - is this  a plotting/browser issue or did you remove those ?

cheers
andy


-------------------------------------------------------------------
Andreas Jung - Purdue University
525 Northwestern Ave, West Lafayette, IN, 47907, USA
Office: +1 765 494 5399<https://exchange.purdue.edu/owa/redir.aspx?SURL=B6NDM6dGBbzM7vE2Kt0soUSUCFE8PqgnzVduRgBgXHQYuPtvrazSCG0AYQBpAGwAdABvADoAYQBuAGoAdQBuAGcAQABwAHUAcgBkAHUAZQAuAGUAZAB1AA..&URL=mailto%3aanjung%40purdue.edu>
-------------------------------------------------------------------
________________________________
