### ISSUE TITLE
New Support Structure Fields

### ISSUE THREAD

**Issue by gneeser** [puhep/pudb2#3]
Let's use this issue to keep a tally of what new fields the support structure objects use. A number were mentioned in the meeting, but I don't recall.

http://inky.physics.purdue.edu/cmsfpix//phase_2/ss_summary.php?id=1

Fields: ???

**Comment by AndySpring** [comment]
Hey Greg
I attempted to load a pdf and then a docx version of the same document for support structure 2 onto the data base under miscellaneous files. It then took me to a page with only the text "file detected" and it does not appear once i go to look for it. I attached a picture with what i see when I attempt to do this.

![database error](https://cloud.githubusercontent.com/assets/26171360/23563628/799f3f22-0015-11e7-8365-deb58b641302.PNG)

**Comment by gneeser** [comment]
Ah, the "file detected" is old debug code I forgot to comment out. It doesn't interfere with processing the data, but I'll comment it out on my next update of the user environment. 

The channel information is currently only tied to each test, but one of the things I'm working on is tying the current channel to the thermal sensor.

**Comment by gneeser** [comment]
Suppressed the debug output
