### ISSUE TITLE
Sheet Information

### ISSUE THREAD

**Issue by gneeser** [puhep/pudb2#5]
Lower priority issue, but eventually we will want to include sheet information in the database.

**Comment by NickHinton** [comment]
No longer low-priority. 

Check https://docs.google.com/spreadsheets/d/1KHqQ6UB9W4ngdO_E-p1TTRFtiZ8SrmYZ_mQ6FoUrzOA/edit#gid=0 for relevant fields.

**Comment by wade31** [comment]
The ability to add new sheets would be nice

**Comment by gneeser** [comment]
Yeah, that's planned. In the meantime, I can manually add a new sheet for you guys to edit. 

May I assume you want PSDL 8ply-1 and PSDL 8ply-2 added?

**Comment by wade31** [comment]
yes both of those would be great

**Comment by gneeser** [comment]
The new sheets are in there. The ability for users to add parts is coming soon.

**Comment by wade31** [comment]
A number field for the bow of the sheets would also be nice

**Comment by gneeser** [comment]
Integer or float?

**Comment by NickHinton** [comment]
Actually for bow it would be better if we could attach an image of the bow map, i.e. 
[PSDL-3ply-2 alex 2017-03-02.pdf](https://github.com/puhep/pudb2/files/834575/PSDL-3ply-2.alex.2017-03-02.pdf)

**Comment by wade31** [comment]
Bow map is attached.


________________________________

**Comment by gneeser** [comment]
How do the names and order of the fields suit you all? Are the names obvious and the order the same as the assembly flow?

@NickHinton @wade31

**Comment by NickHinton** [comment]
Looks good. There is still a strong possibility we want to add more fields or tweak the layout, so I'm going to leave the issue open.

**Comment by NickHinton** [comment]
We need the ability to add new sheets as a user. Is this already there somewhere? If so I can't find it. 

We just made PSDL-3ply-4 and I'd like to add it to the DB.

**Comment by gneeser** [comment]
I added the sheet by hand. I'll see if I can add some part submission pages this week.

**Comment by gneeser** [comment]
Users can now add new sheets to the database

**Comment by NickHinton** [comment]
Can we add fields to the sheet for thickness? I'd like 4 separate fields, 1 for each side (top, bottom, left, right). Floats are fine for this.

**Comment by wade31** [comment]
I tried to upload a file (PDF) of the surface graph measurements for PSDL-3ply-4. The file was uploaded successfully on the gantry computer and I can view it from the summary page, however when Nick tried to view it on his computer he sees an old version of the file. The original and the new file have the same name, the only difference being that the new file has updated axies.

**Comment by gneeser** [comment]
I forgot to mention it on Thursday/Friday, but I pushed out an update fixing the notes and file upload. Let me know if you have any more problems with those things.

I'll also get to work on adding thickness fields to the sheets.

**Comment by NickHinton** [comment]
Can we also get a field for physical location for the sheets (Purdue, Fermilab, CERN, ...?).

**Comment by gneeser** [comment]
What units do you want on the edge thicknesses?

**Comment by NickHinton** [comment]
Microns.

**Comment by gneeser** [comment]
The new sheet information is up - you can add locations and edge thicknesses. Let me know if you encounter problems.
