### ISSUE TITLE
Upload Test Data

### ISSUE THREAD

**Issue by gneeser** [puhep/pudb2#6]
An essential feature of the database will be to upload test data and present it in a coherent and useful manner. Details pending, but let's track them here.

**Comment by gneeser** [comment]
Ideally, we just upload information in an excel file, perhaps with time and sensor info from each sensor on a different sheet. It's very easy to parse and graph information from an excel file, so that would make my life a little easier.

**Comment by AndySpring** [comment]
Hey Greg
Im trying to upload test data from 02/24/17 and I am at the part where I add the sensors. I am trying to put in sensor T10 with does not have X or Y values because it is on the pipe. However, I tried just putting 0,0 to see if that was the issue. It still gave me an error. here is what i encountered

Database error: Invalid SQL: INSERT INTO sensor_test (test_id,thermal_id) VALUES (16, 10) nMySQL Error: 1062 (Duplicate entry '16-10' for key 'PRIMARY') nSession halted.

Thanks

**Comment by gneeser** [comment]
It looks like sensor T10 is already associated with the test, so trying to add it again causes an error. For the time being, I edited T10 to be (0,0) here:

http://inky.physics.purdue.edu/cmsfpix//phase_2_t/test_edit.php?id=16

I'll update the "add sensor page" so that it correctly limits the sensors to ones that haven't been added. Looks like I had an off by one error where if the module only had one sensor, you could add that one sensor again.

**Comment by gneeser** [comment]
Corrected the off by one error. You shouldn't be able to submit any duplicates anymore.

**Comment by wade31** [comment]
Hey if it is possible the ability to submit more than one file at a time would be nice.

**Comment by gneeser** [comment]
About how many will you want to be adding at a time? If it's on the order of, say, 10 or more, then I can add a zip upload option.

**Comment by wade31** [comment]
Probably just 3-5 excel files from testing

**Comment by gneeser** [comment]
Alright, probably not worth having you guys make a zip then. I'll start working on uploading multiple files/pics.

**Comment by gneeser** [comment]
I added the option to upload multiple files at once. It's a little subtle - just control-click to select when the file browser opens.

@wade31 @NickHinton @AndySpring

**Comment by gneeser** [comment]
Did we have any news about testing information? I could get started on code for parsing a csv, xml, or excel file if that would be useful.
