### ISSUE TITLE
Copy Existing Test Geometry & Sensor Channels

### ISSUE THREAD

**Issue by gneeser** [puhep/pudb2#9]
There has been a request to be able to copy an existing test geometry (i.e. the position of sensors) when making/uploading a new test.

The ability to copy sensor channels should also be included in this, as from what I understand, they will not usually change between tests.

**Comment by Purduehep** [comment]
You still working on this? It would be useful, as there are only a few arrangements of sensors so ability to pull from previous set ups would expedite the upload process greatly.

**Comment by gneeser** [comment]
Yeah, this is pending. I've mostly been working on bug fixes and adding new objects to the DB, such as the sheets. 

Will you want a few named geometries, or do we just want to be able to copy from an old test? Eventually, I could add both if you guys would like.

**Comment by gneeser** [comment]
I added the option to import a test geometry (with that test's channels). If you don't copy an existing test geometry, you'll be sent to the add sensor page upon submitting. If you do copy and existing test geometry, you'll be sent straight to the page for editing the test.

If you encounter any problems with this, of course reopen the issue and let me know.
